### ISSUE TITLE
Bot Eklemeye Çalışırken Hata Veriyor

### ISSUE THREAD

**Issue by alphaadevelopment** [vcodes-xyz/bot-list#14]
404
You entered an invalid bot id.
Hatası Veriyor

**Comment by clqu** [comment]
Girdiğiniz bot id'si doğru olmadığı zaman bu hatayı verir. Datadaki verilerinizi kontrol edin.

**Comment by alphaadevelopment** [comment]
bot idsi doğru fakat hep aynı hatayı veriyor 10dan fazla bot üzerinde denedim

**Comment by falsisdev** [comment]
Canım siteye bağlı olan bot ile o bot herhangi bir ortak sunucuda değilse göremiyordur

**Comment by alphaadevelopment** [comment]
Teşşekürler

**Comment by clqu** [comment]
Bot eklerken o hatayı almanız için eklediğiniz id'nin bir bota ait olmaması gerekir ve biz bunu fetch ile yaparız botunuz görmese bile çeker. Yüksek ihtimal ile botunuzun intentleri kapalıdır, onları açtıkdan sonra tekrar eklemeyi deneyin.

**Comment by clqu** [comment]
Daha fazla sorun yaşarsanız anlık cevap vermemiz adına discord sunucumuzua katılabilirsiniz.
https://discord.gg/z7dbzygse4
