### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by anshtyagi0** [vcodes-xyz/bot-list#15]
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name " sweetalert ": name cannot contain leading or trailing spaces; name can only contain URL-friendly characters

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-07-10T03_52_02_201Z-debug.log
exit status 1

**Comment by falsisdev** [comment]
Not a sufficient error message. You have to send the entire console...

**Comment by falsisdev** [comment]
but I think the `sweetalert` package name is wrong in the `package.json` file

**Comment by falsisdev** [comment]
Edit the `package.json` file. Change `︎︎︎︎︎︎
︎sweetalert:` to `sweetalert:`.
