### ISSUE TITLE
"EVENT Add your bot now and join our server for a discord nitro gift to the bot owner who reaches the first 100 votes."

### ISSUE THREAD

**Issue by TeamColaDev** [vcodes-xyz/bot-list#16]
Where do I got to remove this?

**Comment by falsisdev** [comment]
In head.ejs or index.ejs files.

**Comment by falsisdev** [comment]
[Line 31](https://www.github.com/vcodes-xyz/vcodes/tree/v4/src%2Fviews%2Fparts%2Fhead.ejs)
@TeamColaDev

**Comment by clqu** [comment]
Head.ejs
Line: 22 - 42
