### ISSUE TITLE
Serverlist

### ISSUE THREAD

**Issue by anshtyagi0** [vcodes-xyz/bot-list#17]
Serverlist and maintance mode not working

when someone add server it gives an error:
(node:50) UnhandledPromiseRejectionWarning: ReferenceError: sdata is not defined
    at /home/runner/bhbl/src/routers/servers/add.js:38:5
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:50) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

Error when we try to open maintance:
(node:50) UnhandledPromiseRejectionWarning: ReferenceError: client is not defined
    at /home/runner/bhbl/src/routers/admin/maintence.js:26:5
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:50) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

**Comment by clqu** [comment]
Errors are fixed.
