### ISSUE TITLE
Maintance

### ISSUE THREAD

**Issue by anshtyagi0** [vcodes-xyz/bot-list#18]
(node:260) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'channels' of undefined
    at /home/runner/bhbl/src/routers/admin/maintence.js:27:12
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:260) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:260) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by clqu** [comment]
We removed maintence mode so i can't help you, sorry...
