### ISSUE TITLE
Certification Application 

### ISSUE THREAD

**Issue by ghost** [vcodes-xyz/bot-list#26]
When You go to certify a bot you get this error 
<img width="955" alt="Screen Shot 2021-07-18 at 12 52 46 pm" src="https://user-images.githubusercontent.com/77712352/126054125-7263a291-f233-4615-84ad-c842560a65a5.png">

**Comment by clqu** [comment]
Check this commits;
https://github.com/vcodes-xyz/vcodes/commit/56171a655f37566da9d2e1be9d0570190e88cc7a - https://github.com/vcodes-xyz/vcodes/commit/b8944387eaa381b5b532542cf1f60e8344ed835f
