### ISSUE TITLE
Redirect error 

### ISSUE THREAD

**Issue by lordm121** [vcodes-xyz/bot-list#4]
Hi, redirect error can you tell me how to fix it 
![Screenshot_20210501_174754_com android chrome](https://user-images.githubusercontent.com/74502300/116790247-dee3a800-aabb-11eb-8e4c-d5cc9524e4c2.jpg)

**Comment by PasinduDushan** [comment]
Make sure you've added your redirect URI on the `settings.json` file. Ex:- `https://yourdomain.com/callback` and also in the Discord OAuth2 Redirect URL section add the same domain you've added in the `settings.json` file. Hope this helps!

**Comment by TeamColaDev** [comment]
There is no settings.json, there is a config.js

**Comment by falsisdev** [comment]
same things

**Comment by TeamColaDev** [comment]
Doesn't work

**Comment by falsisdev** [comment]
You also need to add callback from Discord Developer Portal. These are classic things that everyone should know, please learn first.

**Comment by PasinduDushan** [comment]
vcodes updated the json file after I put the comment.
