### ISSUE TITLE
How to fix this error?

### ISSUE THREAD

**Issue by builtbyjonas** [vcodes-xyz/bot-list#44]
![Screenshot_20210924-064501_Chrome](https://user-images.githubusercontent.com/81481526/134619689-07ae4125-1ff3-4bfa-9f90-83fa9de8035e.jpg)
![Screenshot_20210924-064513_Chrome](https://user-images.githubusercontent.com/81481526/134619754-1921a0d3-47f0-4d0d-8581-68d4ea10ffce.jpg)

**Comment by compteccharan** [comment]
Yo do npm i at first 😂

**Comment by compteccharan** [comment]
And make .replit run=npm start to node index.js

**Comment by clqu** [comment]
Type **npm i quick.db** in console
