### ISSUE TITLE
Infinite "Joining server" loop.

### ISSUE THREAD

**Issue by Pop-Plays** [vcodes-xyz/bot-list#49]
Joining a server on the bot list just redirects or refreshes the page to well the same page with the countdown.  

Edit:
This only happens when you submit a server with the checkbox "create one for me" under invite link.

**Comment by Borainismyname** [comment]
create one for me is broken i think
but idk

**Comment by ghost** [comment]
this is a well known issue as we can see on the edit page for the code the invite textfield that does work is 
`<input type="text" name="link" id="link" class="form-control" value="<%= data.link ? data.link : '' %>" />`

But on the `servers/add` page its defined under 
`<input type="text" name="link" id="link" class="form-control" placeholder="https://discord.gg/z7dBzygse4"/>` 

but when putting 
`<input type="text" name="link" id="link" class="form-control" value="<%= data.link ? data.link : '' %>" />` 
from edit in place of add it will cause "data" to be undefined so its just a patch more or less to be honest im more a backend server dev then a coder lol but this is the issue caused now if anyone can figure out how to get it working lol @Borainismyname & @Pop-Plays

**Comment by kkakealess** [comment]
I can’t figure it out either
