### ISSUE TITLE
Authorize Error

### ISSUE THREAD

**Issue by builtbyjonas** [vcodes-xyz/bot-list#51]
![Screenshot_20211008-160643_Chrome](https://user-images.githubusercontent.com/81481526/136571904-d656a655-0f86-42d0-bd9d-25ec9bd93db7.jpg) = this shows me the website when I authorized me

How to fix guys pls help

**Comment by Borainismyname** [comment]
you need to open intents , if your intents open check your server id

**Comment by builtbyjonas** [comment]
Where I can find the intents?

**Comment by builtbyjonas** [comment]
or what are the intents in replit?

**Comment by Borainismyname** [comment]
> or what are the intents in replit?

discord dev portal

**Comment by builtbyjonas** [comment]
yeah I have as intents:
https://(MyDomain)/callback

**Comment by Borainismyname** [comment]
> yeah I have as intents: https://(MyDomain)/callback

![image](https://user-images.githubusercontent.com/68708739/138086711-e541434b-d0c1-47f5-9a7c-3fbeb33cc02f.png)
this is the intents not that

**Comment by builtbyjonas** [comment]
I tryed with activated intents but the error is still There ![Screenshot_20211025-081707_Chrome.jpg](https://user-images.githubusercontent.com/81481526/138643978-992213a5-14fc-479c-b414-ea0ce8f0f84e.jpg)

**Comment by kkakealess** [comment]
im the same idk what to do :/

**Comment by kkakealess** [comment]
ok so i figured the error you need to disable **REQUIRES OAUTH2 CODE GRANT** option and make sure the bot is in the server

**Comment by builtbyjonas** [comment]
Thank u so much it worked!

**Comment by kkakealess** [comment]
np
