### ISSUE TITLE
How to fix discord servers bug

### ISSUE THREAD

**Issue by kkakealess** [vcodes-xyz/bot-list#57]
Discord servers don’t work you infinitely have a loop of redirecting…. And counting down is there a possible solution to fix this
![897F43AB-3D1F-45D8-B147-CDE168091FC5](https://user-images.githubusercontent.com/61896024/139092968-d76b8d7f-2841-473c-b691-7c1e73715e9c.jpeg)

**Comment by builtbyjonas** [comment]
You need to edit the server and to paste a new invite link in the invite link section
