### ISSUE TITLE
Activity change

### ISSUE THREAD

**Issue by builtbyjonas** [vcodes-xyz/bot-list#58]
Hello Guys, I need to change the activity from the bot but cant find any script where I can change it can pls anybody tell me the Script name 

Activity: 
![Screenshot_20211027-205709_Discord](https://user-images.githubusercontent.com/81481526/139129591-277e9eb1-67c8-4d1e-90aa-401030659e41.jpg)

**Comment by compteccharan** [comment]
Hahaha very easy one.

But why you want to ?

**Comment by builtbyjonas** [comment]
yes i know that this is easy but i have not found a code where i can change that you can send me the code name

**Comment by compteccharan** [comment]
Ok ima help you

**Comment by compteccharan** [comment]
Go to parentFolder/src/servers/client.js

**Comment by compteccharan** [comment]
And edit this particular line 👍 
Line 47: it starts from and ends in line 50 change it and you're done

`serverClient.on('ready',async () => {
    console.log("[vcodes.xyz/servers]: Bot successfully connected as "+serverClient.user.tag+".");
    serverClient.user.setPresence({ activity: { type: 'WATCHING', name: '-bump & -vote | vcodes.xyz/servers' }, status: "dnd" });
});`

Change it as what you want

Like this if you want

serverClient.on('ready',async () => {
    console.log("[vcodes.xyz/servers]: Bot successfully connected as "+serverClient.user.tag+".");
    serverClient.user.setPresence({ activity: { type: 'WATCHING', name: '-bump & -vote | yourdomain.xyz/servers' }, status: "dnd" });
});

WATCHING, LISTENING, STREAMING and PLAYING can be used in the place of watching

And dnd , on,  can also be used

**Comment by builtbyjonas** [comment]
Thank u for your help but the activity you sent me is for the server offered that i already have

**Comment by builtbyjonas** [comment]
I need the code with the activity of the main bot

**Comment by compteccharan** [comment]
Hmm i will try to find it
