### ISSUE TITLE
Link Cover

### ISSUE THREAD

**Issue by builtbyjonas** [vcodes-xyz/bot-list#60]
Hello can anybody tell me how I can change this image:
![Screenshot_20211110-154034_Discord](https://user-images.githubusercontent.com/81481526/141134082-15feef7f-9595-4dbf-a6da-13feed89cdee.jpg)

**Comment by dhvitish** [comment]
It's in this file https://github.com/vcodes-xyz/vcodes/blob/v4/src/views/parts/foot.ejs

**Comment by builtbyjonas** [comment]
Thank you
