### ISSUE TITLE
countries flags images do not load 

### ISSUE THREAD

**Issue by builtbyjonas** [vcodes-xyz/bot-list#61]
Hello Guys can anybody tell me how I can fix this:

Main Site:
![Screenshot_20211111-203949_Chrome](https://user-images.githubusercontent.com/81481526/141361599-81d5face-0afa-4c7f-98a3-498f53e21aca.jpg)

Admin Panel:
![Screenshot_20211111-203917_Chrome](https://user-images.githubusercontent.com/81481526/141361652-1bf514b4-f489-4b85-9816-f5f0ca5588bf.jpg)

**Comment by anshtyagi0** [comment]
This is because https://countryflags.io is down.
