### ISSUE TITLE
Removing Bots in admin panel

### ISSUE THREAD

**Issue by JsmliYT** [vcodes-xyz/bot-list#68]
I am unable to delete a bot VIA the admin panel, when I try to do so it gets stuck on an infinite refresh loop with the website, how do I fix this?

**Comment by JonBoyen** [comment]
![image](https://user-images.githubusercontent.com/73805411/146522329-5240ea40-c7b3-4ff8-a9ac-c13beaa67e17.png)

Video to the issue:
[https://youtu.be/RcWh-Dg6Z0w](url)

**Comment by builtbyjonas** [comment]
Do you have connected your mongo db?

**Comment by builtbyjonas** [comment]
if yes then i think you need to use this version.
▪︎ this version here: https://github.com/vcodes-xyz/vcodes
