### ISSUE TITLE
Login Error 

### ISSUE THREAD

**Issue by ExoticBotlist** [vcodes-xyz/bot-list#70]
Hello I am having this login error.
![Screenshot 2021-12-23 4 22 11 PM](https://user-images.githubusercontent.com/88468527/147292514-27b2a0ed-5f61-48d1-9ebe-832384666808.png)

**Comment by ExoticBotlist** [comment]
can someone please tell me how to fix this asap?

**Comment by builtbyjonas** [comment]
Make sure to add an guild id where u and the bot are in
