### ISSUE TITLE
error css

### ISSUE THREAD

**Issue by LucasB25** [vcodes-xyz/bot-list#89]
Css does not work

![image](https://user-images.githubusercontent.com/50886682/159129359-3fbcd0f2-9ff3-4c51-83a7-c35cc9e149be.png)

**Comment by AstroApex22** [comment]
https://github.com/vcodes-xyz/vcodes/issues/47

**Comment by LucasB25** [comment]
> #47

no I looked at this version after the correction

**Comment by builtbyjonas** [comment]
is in src/views/assets/css an bulma.css and bootstrap.css and style.css??? if not pls add that one which is not in there

**Comment by LucasB25** [comment]
> is in src/views/assets/css an bulma.css and bootstrap.css and style.css??? if not pls add that one which is not in there

What do you mean

**Comment by builtbyjonas** [comment]
are there these files in src/views/assets/css?
![grafik](https://user-images.githubusercontent.com/81481526/159296789-c24471fc-f5ca-4665-9222-6dd7dbde8a1c.png)

**Comment by builtbyjonas** [comment]
if one of the file is not there pls create it and put in the code

**Comment by LucasB25** [comment]
> if one of the file is not there pls create it and put in the code

Yes 
![image](https://user-images.githubusercontent.com/50886682/159304909-72c77626-e1bf-4bb5-96e8-53abef12f24e.png)

**Comment by builtbyjonas** [comment]
so every file is there?
send me a screenshot of src/views/parts/links.ejs

**Comment by LucasB25** [comment]
> so every file is there? YES
> send me a screenshot of src/views/parts/links.ejs

![image](https://user-images.githubusercontent.com/50886682/159423518-4651685b-0043-4c12-a268-24e8c11146bd.png)

**Comment by builtbyjonas** [comment]
> > so every file is there? YES
> > send me a screenshot of src/views/parts/links.ejs
> 
> ![image](https://user-images.githubusercontent.com/50886682/159423518-4651685b-0043-4c12-a268-24e8c11146bd.png)

In line 2 and 3 are an url behind href=. Change the "<%- req.get('host') %>" to your host so if you never changed the site port paste in the line 2: ```https://localhost:3000/css/bulma.css```

and paste in the 3 line: ```https://localhost:3000/css/boostrap.csss```


then it should work
