### ISSUE TITLE
slow loading of pages 

### ISSUE THREAD

**Issue by LucasB25** [vcodes-xyz/bot-list#93]
I noticed that loading the bot list was quite slow from the browsers

**Comment by AcedDown** [comment]
not our problem that your WiFi is shit

**Comment by LucasB25** [comment]
so nah nothing to do with my wifi, i’m fibrous and I never have them worry about more than other developer saying the same thing. This slowdown problem simply affects the Bots page when there are several as well as the user profile

**Comment by LucasB25** [comment]
> not our problem that your WiFi is shit

Nothing to do with my wi-fi, I am under fiber and I never have them any worries then other developers say the same thing, when bots appear on the site there are slowdowns on the index page. This slowdown problem simply affects the page where there are Bots when there are several as well as the user profile

**Comment by LucasB25** [comment]
The problem comes from the site code loading unnecessary elements from the database so it takes time
