### ISSUE TITLE
login yapamıyorum

### ISSUE THREAD

**Issue by emreyusuf25** [vcodes-xyz/bot-list#97]
altyapıyı indirip sanal sunucuma kurdum gerekli bilgileri girdim callback url sini developer portala da girdim siteden login butonuna basınca discord a yönlendiriyor yetkilendirdikten sonra geri siteye gönderiyor ancak sitede login olmuyor girdikten sonra kodu veriyor ancak giriş yapmamış olarak görnüyor ve terminale hata atmıyor
![Ekran Alıntısı](https://user-images.githubusercontent.com/82025143/181494153-d8f52c6a-8c04-4aa7-bc32-246de899f868.PNG)

**Comment by clqu** [comment]
Callback adresi yanlış girilmiş. Configi tekrardan doldurun.
